### ISSUE TITLE
subprocess.CalledProcessError: Command '['xprintidle']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by Braveatom** [mssever/sleep-inhibit#11]
Hi there, I'm trying to get your app to run on a relatively fresh install of 15.04. I've added the dependences, but get the error below after running 'python3 sleep_inhibit'. Any ideas what I'm doing wrong?

```
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
couldn't open display
Traceback (most recent call last):
  File "sleep_inhibit", line 39, in <module>
    exit(main())
  File "/home/home/sleep-inhibit-1.0.0-beta/sleepinhibit/startup.py", line 76, in main
    if not dependencies_are_satisfied():
  File "/home/home/sleep-inhibit-1.0.0-beta/sleepinhibit/startup.py", line 31, in dependencies_are_satisfiedyapayne/Web2Executable/issues
    util.cmd_output(['xprintidle'])
  File "/home/home/sleep-inhibit-1.0.0-beta/sleepinhibit/util.py", line 26, in cmd_output
    return subprocess.check_output(*args, **kwargs).decode('utf-8').strip()
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['xprintidle']' returned non-zero exit status 1
```
### Edit from dev

The ultimate solution here is to have a way to inhibit sleep which doesn't depend on having an X session. Any contributions along that front would be welcomed.

**Comment by mssever** [comment]
Hi, could you tell me what you get when you type `xprintidle` into the command line? Also, it appears that you're using Mir instead of X windows. If so, I don't know whether X utilities will work with Mir.

**Comment by Braveatom** [comment]
Sure, will do - I wont be at the machine for a couple of hours. I have realised that I said it was Ubuntu 15.04 - its not, its 15.10, sorry.

**Comment by Braveatom** [comment]
Heres the output from that - "couldn't open display"

Its odd, I haven't knowingly installed anything out of the ordinary - fresh install, Netatalk, Avahi, Plex - pretty much it - its a back up machine and file server.

**Comment by mssever** [comment]
If this is a server, and you can't open the display, are you logged in to a graphical session, or to a CLI-only session? Sleep Inhibitor depends on having a graphical interface available; many parts of the program will fail absent that.

I may look into how to make Sleep Inhibitor work without a GUI, but that would be a non-trivial amount of work and could take a while.

**Comment by mssever** [comment]
I've got a partial fix for this issue. Would you mind testing it? [Go to this branch](https://github.com/mssever/sleep-inhibit/tree/bug11) and click the green button labeled `Clone or download`.

If I've understood your situation correctly, you should receive an error message which diagnoses the problem, and you should be able to know what to do about it.
